# conda env create -n <name> --file <thisfile>.yml

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - opencv=3.4
  - numpy=1.19
  - pathlib=1.0
  - pip=20.2
  - pixman=0.40
  - pyqt=5.9
  - scikit-learn=0.23.*
  - pip:
    - git+git://github.com/fjean/pymeanshift.git