# conda env create -n <name> --file <thisfile>.yml
channels:
  -conda-forge
  - defaults
dependencies:
  - numpy=1.19  
  - opencv=3.4  
  - pathlib=1.0  
  - pip=20.2
  - pixman=0.40
  - pyqt=5.9
  - python=3.7   
